apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-mysql
  namespace: sqldb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - name: mysql
        image: 508327803984.dkr.ecr.us-east-1.amazonaws.com/myimages:mydb-v1.0
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: "pw"
        ports:
        - containerPort: 3306