apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-frontend
  namespace: webapp
spec:
  replicas: 3
  selector:
    matchLabels:
      app: employees
      version: v1
  template:
    metadata:
      labels:
        app: employees
        version: v1
    spec:
      containers:
      - name: frontend
        image: 508327803984.dkr.ecr.us-east-1.amazonaws.com/myimages:myapp-v1.0
        env:
        - name: GET_HOSTS_FROM
          value: "dns"
        - name: DBHOST
          value: "mysql-service.sqldb.svc.cluster.local"
        - name: DBPORT
          value: "3306"
        - name: DBUSER
          valueFrom:
            secretKeyRef:
              name: db-mysecret
              key: user
        - name: DATABASE
          value: "employees"
        - name: DBPWD
          valueFrom:
            secretKeyRef:
              name: db-mysecret
              key: password
        - name: APP_COLOR
          value: "blue"
        ports:
        - containerPort: 8080
          protocol: TCP
      dnsPolicy: ClusterFirst
      restartPolicy: Always