apiVersion: v1
kind: Pod
metadata:
  name: mysql
  namespace: sqldb
spec:
  containers:
  - name: mysql
    image: 508327803984.dkr.ecr.us-east-1.amazonaws.com/myimages:mydb-v1.0
    env:
    - name: MYSQL_ROOT_PASSWORD
      value: "pw"
    ports:
    - containerPort: 3306
      protocol: TCP
    resources:
      requests:
        cpu: 100m
        memory: 100Mi
  dnsPolicy: ClusterFirst
  restartPolicy: Always