apiVersion: v1
kind: Service
metadata:
  name: servicenpv2-frontend
  namespace: webapp
spec:
  selector:
    app: employees
    version: v2
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8080
      nodePort: 30000
  type: NodePort