apiVersion: v1
kind: Service
metadata:
  name: servicenp-frontend
  namespace: webapp
spec:
  selector:
    app: employees
    version: v1
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30001
  type: NodePort